Bootstrap: docker
From: nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04

%post
        apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        wget \
        gnupg \
        python3-pip \
        python3-dev \
        python-is-python3 \
        git \
        ffmpeg \
        libnvidia-gl-560 \
        libvulkan1 \
        vulkan-tools \
        software-properties-common
        
        apt-get clean
        rm -rf /var/lib/apt/lists/*

        mkdir /project && cd /project

        # Install octo/SimplerEnv python requirements
        wget https://raw.githubusercontent.com/simpler-env/SimplerEnv/refs/heads/main/requirements_full_install.txt
        pip install tensorflow==2.15.0
        pip install -r requirements_full_install.txt && rm requirements_full_install.txt
        pip install tensorflow[and-cuda]==2.15.1 
        pip install git+https://github.com/nathanrooy/simulated-annealing 
        pip install numpy==1.24.4 
        pip install --upgrade "jax[cuda11_pip]==0.4.20" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
        # Upgrade pip so we can install SimplerEnv later
        pip3 install -U pip

%environment
        SHELL=/bin/bash
        export SHELL
        export NVIDIA_DRIVER_CAPABILITIES=all

%runscript
        exec /bin/sh "$@"